version: "3.9"

services:
#  postgres:
#    image: postgres
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
#      timeout: 45s
#      interval: 10s
#      retries: 10
#    restart: always
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=password
#      - APP_DB_USER=docker
#      - APP_DB_PASS=docker
#      - APP_DB_NAME=docker
#    volumes:
#      - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
#    ports:
#      - 5432:5432
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#  minio:
#    image: minio/minio:latest
#    command: server --console-address ":9001" /data/
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: minio
#      MINIO_ROOT_PASSWORD: minio123
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3

  movie:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"

  dockergo:
    build:
      context: .
      dockerfile: ./Dockerfile.multistage
    links:
      - movie:movie
#    links:
#      - postgres:postgres
#      - redis:redis
#      - minio:minio
    ports:
      - "1323:1323"

#  nginx:
#    image: nginx:latest
#    links:
#      - dockergo:dockergo
#      - minio:minio
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    ports:
#      - "8000:80"
