// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: compilations.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Genre   []string `protobuf:"bytes,3,rep,name=Genre,proto3" json:"Genre,omitempty"`
	Picture string   `protobuf:"bytes,4,opt,name=Picture,proto3" json:"Picture,omitempty"`
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{0}
}

func (x *MovieInfo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MovieInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieInfo) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *MovieInfo) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type MovieCompilation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Movies []*MovieInfo `protobuf:"bytes,2,rep,name=Movies,proto3" json:"Movies,omitempty"`
}

func (x *MovieCompilation) Reset() {
	*x = MovieCompilation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieCompilation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieCompilation) ProtoMessage() {}

func (x *MovieCompilation) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieCompilation.ProtoReflect.Descriptor instead.
func (*MovieCompilation) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{1}
}

func (x *MovieCompilation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieCompilation) GetMovies() []*MovieInfo {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MovieCompilationsArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieCompilations []*MovieCompilation `protobuf:"bytes,1,rep,name=MovieCompilations,proto3" json:"MovieCompilations,omitempty"`
}

func (x *MovieCompilationsArr) Reset() {
	*x = MovieCompilationsArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieCompilationsArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieCompilationsArr) ProtoMessage() {}

func (x *MovieCompilationsArr) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieCompilationsArr.ProtoReflect.Descriptor instead.
func (*MovieCompilationsArr) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{2}
}

func (x *MovieCompilationsArr) GetMovieCompilations() []*MovieCompilation {
	if x != nil {
		return x.MovieCompilations
	}
	return nil
}

type GetMainCompilationsOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMainCompilationsOptions) Reset() {
	*x = GetMainCompilationsOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMainCompilationsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMainCompilationsOptions) ProtoMessage() {}

func (x *GetMainCompilationsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMainCompilationsOptions.ProtoReflect.Descriptor instead.
func (*GetMainCompilationsOptions) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{3}
}

type GetByIDOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetByIDOptions) Reset() {
	*x = GetByIDOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIDOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDOptions) ProtoMessage() {}

func (x *GetByIDOptions) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDOptions.ProtoReflect.Descriptor instead.
func (*GetByIDOptions) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIDOptions) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetByIDOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByIDOptions) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetCompilationOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetCompilationOptions) Reset() {
	*x = GetCompilationOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compilations_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCompilationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompilationOptions) ProtoMessage() {}

func (x *GetCompilationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_compilations_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompilationOptions.ProtoReflect.Descriptor instead.
func (*GetCompilationOptions) Descriptor() ([]byte, []int) {
	return file_compilations_proto_rawDescGZIP(), []int{5}
}

func (x *GetCompilationOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCompilationOptions) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_compilations_proto protoreflect.FileDescriptor

var file_compilations_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x4a, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x06, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x22, 0x57, 0x0a, 0x14, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x41, 0x72, 0x72, 0x12, 0x3f, 0x0a, 0x11, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x32,
	0xa0, 0x03, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x69, 0x6e,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x15, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x41, 0x72, 0x72,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x79, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x11, 0x2e, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12,
	0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x42,
	0x79, 0x59, 0x65, 0x61, 0x72, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x11, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_compilations_proto_rawDescOnce sync.Once
	file_compilations_proto_rawDescData = file_compilations_proto_rawDesc
)

func file_compilations_proto_rawDescGZIP() []byte {
	file_compilations_proto_rawDescOnce.Do(func() {
		file_compilations_proto_rawDescData = protoimpl.X.CompressGZIP(file_compilations_proto_rawDescData)
	})
	return file_compilations_proto_rawDescData
}

var file_compilations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_compilations_proto_goTypes = []interface{}{
	(*MovieInfo)(nil),                  // 0: MovieInfo
	(*MovieCompilation)(nil),           // 1: MovieCompilation
	(*MovieCompilationsArr)(nil),       // 2: MovieCompilationsArr
	(*GetMainCompilationsOptions)(nil), // 3: GetMainCompilationsOptions
	(*GetByIDOptions)(nil),             // 4: GetByIDOptions
	(*GetCompilationOptions)(nil),      // 5: GetCompilationOptions
}
var file_compilations_proto_depIdxs = []int32{
	0, // 0: MovieCompilation.Movies:type_name -> MovieInfo
	1, // 1: MovieCompilationsArr.MovieCompilations:type_name -> MovieCompilation
	3, // 2: MovieCompilations.GetMainCompilations:input_type -> GetMainCompilationsOptions
	4, // 3: MovieCompilations.GetByGenre:input_type -> GetByIDOptions
	4, // 4: MovieCompilations.GetByCountry:input_type -> GetByIDOptions
	4, // 5: MovieCompilations.GetByMovie:input_type -> GetByIDOptions
	4, // 6: MovieCompilations.GetByPerson:input_type -> GetByIDOptions
	4, // 7: MovieCompilations.GetTopByYear:input_type -> GetByIDOptions
	5, // 8: MovieCompilations.GetTop:input_type -> GetCompilationOptions
	2, // 9: MovieCompilations.GetMainCompilations:output_type -> MovieCompilationsArr
	1, // 10: MovieCompilations.GetByGenre:output_type -> MovieCompilation
	1, // 11: MovieCompilations.GetByCountry:output_type -> MovieCompilation
	1, // 12: MovieCompilations.GetByMovie:output_type -> MovieCompilation
	1, // 13: MovieCompilations.GetByPerson:output_type -> MovieCompilation
	1, // 14: MovieCompilations.GetTopByYear:output_type -> MovieCompilation
	1, // 15: MovieCompilations.GetTop:output_type -> MovieCompilation
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_compilations_proto_init() }
func file_compilations_proto_init() {
	if File_compilations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_compilations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compilations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieCompilation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compilations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieCompilationsArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compilations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMainCompilationsOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compilations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIDOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compilations_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCompilationOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compilations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compilations_proto_goTypes,
		DependencyIndexes: file_compilations_proto_depIdxs,
		MessageInfos:      file_compilations_proto_msgTypes,
	}.Build()
	File_compilations_proto = out.File
	file_compilations_proto_rawDesc = nil
	file_compilations_proto_goTypes = nil
	file_compilations_proto_depIdxs = nil
}
