global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "server"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:1323' ]
  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']

rule_files:
  - "alert.yml"