// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock_movie is a generated GoMock package.
package mock_movie

import (
	internal "myapp/internal"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockService) GetByID(id int) (*internal.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*internal.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), id)
}

// GetMainMovie mocks base method.
func (m *MockService) GetMainMovie() (*internal.MainMovieInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainMovie")
	ret0, _ := ret[0].(*internal.MainMovieInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainMovie indicates an expected call of GetMainMovie.
func (mr *MockServiceMockRecorder) GetMainMovie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainMovie", reflect.TypeOf((*MockService)(nil).GetMainMovie))
}

// GetRandom mocks base method.
func (m *MockService) GetRandom(limit, offset int) ([]internal.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", limit, offset)
	ret0, _ := ret[0].([]internal.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockServiceMockRecorder) GetRandom(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockService)(nil).GetRandom), limit, offset)
}
